// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type PartnerStatus string

const (
	PartnerStatusPending   PartnerStatus = "pending"
	PartnerStatusActive    PartnerStatus = "active"
	PartnerStatusInactive  PartnerStatus = "inactive"
	PartnerStatusSuspended PartnerStatus = "suspended"
)

func (e *PartnerStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PartnerStatus(s)
	case string:
		*e = PartnerStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PartnerStatus: %T", src)
	}
	return nil
}

type NullPartnerStatus struct {
	PartnerStatus PartnerStatus `json:"partner_status"`
	Valid         bool          `json:"valid"` // Valid is true if PartnerStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPartnerStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PartnerStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PartnerStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPartnerStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PartnerStatus), nil
}

type Form struct {
	ID             uuid.UUID          `json:"id"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	TemplateID     pgtype.UUID        `json:"template_id"`
	Title          string             `json:"title"`
	Description    pgtype.Text        `json:"description"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type FormField struct {
	ID          uuid.UUID          `json:"id"`
	FormID      uuid.UUID          `json:"form_id"`
	SectionID   uuid.UUID          `json:"section_id"`
	FieldType   string             `json:"field_type"`
	Label       string             `json:"label"`
	Key         string             `json:"key"`
	Description pgtype.Text        `json:"description"`
	Placeholder pgtype.Text        `json:"placeholder"`
	IsRequired  bool               `json:"is_required"`
	SortOrder   int32              `json:"sort_order"`
	Validation  []byte             `json:"validation"`
	Options     []byte             `json:"options"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type FormSection struct {
	ID          uuid.UUID          `json:"id"`
	FormID      uuid.UUID          `json:"form_id"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	SortOrder   int32              `json:"sort_order"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type FormSubmission struct {
	ID          uuid.UUID          `json:"id"`
	FormID      uuid.UUID          `json:"form_id"`
	PartnerID   uuid.UUID          `json:"partner_id"`
	SubmittedBy pgtype.UUID        `json:"submitted_by"`
	Status      string             `json:"status"`
	Responses   []byte             `json:"responses"`
	SubmittedAt pgtype.Timestamptz `json:"submitted_at"`
	ReviewedAt  pgtype.Timestamptz `json:"reviewed_at"`
	ReviewedBy  pgtype.UUID        `json:"reviewed_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type FormTemplate struct {
	ID          uuid.UUID          `json:"id"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	Category    pgtype.Text        `json:"category"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Organization struct {
	ID                  uuid.UUID          `json:"id"`
	Name                string             `json:"name"`
	Description         pgtype.Text        `json:"description"`
	WebsiteUrl          pgtype.Text        `json:"website_url"`
	Industry            pgtype.Text        `json:"industry"`
	TeamSize            pgtype.Text        `json:"team_size"`
	PrimaryCustomerType pgtype.Text        `json:"primary_customer_type"`
	OwnerRole           string             `json:"owner_role"`
	IsActive            bool               `json:"is_active"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type Partner struct {
	ID             uuid.UUID          `json:"id"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	Name           string             `json:"name"`
	Email          string             `json:"email"`
	Phone          pgtype.Text        `json:"phone"`
	Status         NullPartnerStatus  `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type PartnerInvitation struct {
	ID        uuid.UUID          `json:"id"`
	PartnerID uuid.UUID          `json:"partner_id"`
	Email     string             `json:"email"`
	Token     string             `json:"token"`
	InvitedBy uuid.UUID          `json:"invited_by"`
	RoleID    uuid.UUID          `json:"role_id"`
	Status    string             `json:"status"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Role struct {
	ID          uuid.UUID          `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID                    uuid.UUID          `json:"id"`
	FirstName             string             `json:"first_name"`
	LastName              string             `json:"last_name"`
	Email                 string             `json:"email"`
	Password              string             `json:"password"`
	Phone                 string             `json:"phone"`
	OrganizationID        pgtype.UUID        `json:"organization_id"`
	RoleID                uuid.UUID          `json:"role_id"`
	AvatarUrl             pgtype.Text        `json:"avatar_url"`
	IsActive              bool               `json:"is_active"`
	EmailVerified         bool               `json:"email_verified"`
	PhoneVerified         bool               `json:"phone_verified"`
	RefreshToken          pgtype.Text        `json:"refresh_token"`
	RefreshTokenExpiresAt pgtype.Timestamptz `json:"refresh_token_expires_at"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	PartnerID             pgtype.UUID        `json:"partner_id"`
}
