// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Role struct {
	ID          uuid.UUID          `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID                    uuid.UUID          `json:"id"`
	FirstName             string             `json:"first_name"`
	LastName              string             `json:"last_name"`
	Email                 string             `json:"email"`
	Password              string             `json:"password"`
	Phone                 string             `json:"phone"`
	RoleID                uuid.UUID          `json:"role_id"`
	AvatarUrl             pgtype.Text        `json:"avatar_url"`
	IsActive              bool               `json:"is_active"`
	EmailVerified         bool               `json:"email_verified"`
	PhoneVerified         bool               `json:"phone_verified"`
	RefreshToken          pgtype.Text        `json:"refresh_token"`
	RefreshTokenExpiresAt pgtype.Timestamptz `json:"refresh_token_expires_at"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}
