// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CloneTemplateToForm(ctx context.Context, arg CloneTemplateToFormParams) (Form, error)
	// ============================================================
	// FORMS
	// ============================================================
	CreateForm(ctx context.Context, arg CreateFormParams) (Form, error)
	// ============================================================
	// FORM FIELDS
	// ============================================================
	CreateFormField(ctx context.Context, arg CreateFormFieldParams) (FormField, error)
	// ============================================================
	// FORM SECTIONS
	// ============================================================
	CreateFormSection(ctx context.Context, arg CreateFormSectionParams) (FormSection, error)
	// ============================================================
	// FORM SUBMISSIONS
	// ============================================================
	CreateFormSubmission(ctx context.Context, arg CreateFormSubmissionParams) (FormSubmission, error)
	// ============================================================
	// FORM TEMPLATES
	// ============================================================
	CreateFormTemplate(ctx context.Context, arg CreateFormTemplateParams) (FormTemplate, error)
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error)
	CreatePartnerInvitation(ctx context.Context, arg CreatePartnerInvitationParams) (PartnerInvitation, error)
	CreatePartners(ctx context.Context, arg CreatePartnersParams) (Partner, error)
	// ============================================================
	// ROLES
	// ============================================================
	CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteForm(ctx context.Context, id uuid.UUID) error
	DeleteFormField(ctx context.Context, id uuid.UUID) error
	DeleteFormSection(ctx context.Context, id uuid.UUID) error
	DeleteFormTemplate(ctx context.Context, id uuid.UUID) error
	DeleteOrganization(ctx context.Context, id uuid.UUID) error
	DeletePartner(ctx context.Context, id uuid.UUID) error
	DeleteRole(ctx context.Context, id uuid.UUID) (Role, error)
	DeleteUser(ctx context.Context, id uuid.UUID) error
	GetAllFormTemplates(ctx context.Context) ([]FormTemplate, error)
	GetAllOrganizations(ctx context.Context) ([]Organization, error)
	GetAllPartners(ctx context.Context) ([]Partner, error)
	GetFormByID(ctx context.Context, id uuid.UUID) (Form, error)
	GetFormFieldByID(ctx context.Context, id uuid.UUID) (FormField, error)
	GetFormFieldsByFormID(ctx context.Context, formID pgtype.UUID) ([]FormField, error)
	GetFormFieldsBySectionID(ctx context.Context, sectionID uuid.UUID) ([]FormField, error)
	GetFormSectionByID(ctx context.Context, id uuid.UUID) (FormSection, error)
	GetFormSectionsByFormID(ctx context.Context, formID pgtype.UUID) ([]FormSection, error)
	GetFormSubmissionByID(ctx context.Context, id uuid.UUID) (FormSubmission, error)
	GetFormSubmissionsByFormID(ctx context.Context, formID uuid.UUID) ([]FormSubmission, error)
	GetFormSubmissionsByPartnerID(ctx context.Context, partnerID uuid.UUID) ([]FormSubmission, error)
	GetFormTemplateByID(ctx context.Context, id uuid.UUID) (FormTemplate, error)
	GetFormsByOrg(ctx context.Context, organizationID uuid.UUID) ([]Form, error)
	GetOrganizationById(ctx context.Context, id uuid.UUID) (Organization, error)
	GetOrganizationByUserID(ctx context.Context, dollar_1 uuid.UUID) (Organization, error)
	GetPartnerById(ctx context.Context, id uuid.UUID) (Partner, error)
	GetPartnerByUserID(ctx context.Context, dollar_1 uuid.UUID) (Partner, error)
	GetPartnerInvitationByToken(ctx context.Context, token string) (PartnerInvitation, error)
	GetPartnerInvitationsByPartner(ctx context.Context, partnerID uuid.UUID) ([]PartnerInvitation, error)
	GetPartnersByOrg(ctx context.Context, organizationID uuid.UUID) ([]Partner, error)
	GetRoleByID(ctx context.Context, id uuid.UUID) (Role, error)
	GetRoleByName(ctx context.Context, name string) (Role, error)
	GetTemplateFieldsByTemplateID(ctx context.Context, templateID pgtype.UUID) ([]FormField, error)
	GetTemplateSectionsByTemplateID(ctx context.Context, templateID pgtype.UUID) ([]FormSection, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByRefreshToken(ctx context.Context, refreshToken pgtype.Text) (User, error)
	ListRoles(ctx context.Context) ([]Role, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	ReviewFormSubmission(ctx context.Context, arg ReviewFormSubmissionParams) (FormSubmission, error)
	RevokeRefreshToken(ctx context.Context, id uuid.UUID) error
	UpdateForm(ctx context.Context, arg UpdateFormParams) (Form, error)
	UpdateFormField(ctx context.Context, arg UpdateFormFieldParams) (FormField, error)
	UpdateFormSection(ctx context.Context, arg UpdateFormSectionParams) (FormSection, error)
	UpdateFormSubmission(ctx context.Context, arg UpdateFormSubmissionParams) (FormSubmission, error)
	UpdateFormTemplate(ctx context.Context, arg UpdateFormTemplateParams) (FormTemplate, error)
	UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) (Organization, error)
	UpdatePartner(ctx context.Context, arg UpdatePartnerParams) (Partner, error)
	UpdatePartnerInvitationStatus(ctx context.Context, arg UpdatePartnerInvitationStatusParams) (PartnerInvitation, error)
	UpdateRole(ctx context.Context, arg UpdateRoleParams) (Role, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserOrganization(ctx context.Context, arg UpdateUserOrganizationParams) (User, error)
	UpdateUserPartner(ctx context.Context, arg UpdateUserPartnerParams) (User, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error)
	UpdateUserRefreshToken(ctx context.Context, arg UpdateUserRefreshTokenParams) (User, error)
}

var _ Querier = (*Queries)(nil)
